version: '3.8'

services:
  ffc-demo-message-queue:
    container_name: ffc-demo-message-queue
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    networks:
      - ffc-demo
    ports:
      - "8161:8161" # Web server
      - "5672:5672" # AMQP
    volumes:
      - message-queue-data:/var/lib/artemis/data
      - message-queue-tmp:/var/lib/artemis/tmp
      - message-queue-etc:/var/lib/artemis/etc
      - message-queue-etc-override:/var/lib/artemis/etc-override
      - message-queue-lock:/var/lib/artemis/lock
      - message-queue-jmx:/opt/jmx-exporter/etc-override

networks:
  ffc-demo:
    external: true

volumes:
  message-queue-data: {}
  message-queue-tmp: {}
  message-queue-etc: {}
  message-queue-etc-override: {}
  message-queue-lock: {}
  message-queue-jmx: {}
