#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

(
  cd "${projectRoot}"

  helm delete --purge \
    ffc-demo-message-queue \
    ffc-demo-postgres
)
