#!/usr/bin/env sh

##
# Build script
#
# Build the services managed by this project.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}/services"

  printf "\nBuilding services\n"

  docker-compose \
    -f ../ffc-demo-web/docker-compose.yaml \
    -f ../ffc-demo-web/docker-compose.override.yaml \
  build $@

  docker-compose \
    -f ../ffc-demo-claim-service/docker-compose.yaml \
    -f ../ffc-demo-claim-service/docker-compose.override.yaml \
  build $@

  docker-compose \
    -f ../ffc-demo-payment-service/docker-compose.yaml \
    -f ../ffc-demo-payment-service/docker-compose.override.yaml \
  build $@

  docker-compose \
    -f ../ffc-demo-payment-service-core/docker-compose.yaml \
    -f ../ffc-demo-payment-service-core/docker-compose.override.yaml \
  build $@

  docker-compose \
    -f ../ffc-demo-calculation-service/docker-compose.yaml \
    -f ../ffc-demo-calculation-service/docker-compose.override.yaml \
  build $@

  docker-compose \
    -f ../ffc-demo-payment-web/docker-compose.yaml \
    -f ../ffc-demo-payment-web/docker-compose.override.yaml \
  build $@
)
