#!/usr/bin/env sh

##
# Build script
#
# Build the services managed by this project.
# Expects each service to have a build script at `scripts/build`.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}/services"

  ffc-demo-web/scripts/build
  ffc-demo-api-gateway/scripts/build
  ffc-demo-calculation-service/scripts/build
  ffc-demo-claim-service/scripts/build
  ffc-demo-payment-service/scripts/build
  ffc-demo-user-service/scripts/build
)
