#!/usr/bin/env sh

##
# Setup script
#
# Clone and set up this project's microservice repositories.
# Expects each service to have a setup script at `scripts/setup`.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}/services"

  echo "Cloning repositories"
  test -d "mine-support" || git clone git@github.com:DEFRA/mine-support.git
  test -d "mine-support-api-gateway" || git clone git@github.com:DEFRA/mine-support-api-gateway.git
  test -d "mine-support-calculation-service" || git clone git@github.com:DEFRA/mine-support-calculation-service.git
  test -d "mine-support-claim-service" || git clone git@github.com:DEFRA/mine-support-claim-service.git
  test -d "mine-support-payment-service" || git clone git@github.com:DEFRA/mine-support-payment-service.git
  test -d "mine-support-user-service" || git clone git@github.com:DEFRA/mine-support-user-service.git

  echo "Running repository setup scripts"
  (cd "mine-support" && scripts/setup)
  (cd "mine-support-api-gateway" && scripts/setup)
  (cd "mine-support-calculation-service" && scripts/setup)
  (cd "mine-support-claim-service" && scripts/setup)
  (cd "mine-support-payment-service" && scripts/setup)
  (cd "mine-support-user-service" && scripts/setup)
)
