#!/usr/bin/env sh

##
# Start Core script
#
# Start the supporting services this repository provides.
# This enables other project services to be started one-by-one and
# connected to shared message queues and other supporting services.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

# Check whether ffc-demo network needs creating
if [ -z "$(docker network ls --filter name=^ffc-demo$ --format={{.Name}})" ]; then
  echo "Creating ffc-demo Docker network"
  docker network create ffc-demo
fi

(
  cd "${projectRoot}"

  docker-compose up $@
)
