#!/usr/bin/env sh

##
# Stop Core script
#
# Stop the supporting services this repository provides.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"

  docker-compose down -v
)

# Check whether mine-support network exists and is no longer in use
if [ ! -z "$(docker network ls --filter name=^mine-support$ --format={{.Name}})" ] \
  && [ "$(docker network inspect -f {{.Containers}} mine-support &>/dev/null)" = "map[]" ] \
; then
  echo "Removing mine-support network"
  docker network rm mine-support
fi
