#!/usr/bin/env sh

##
# Stop script
#
# Stop all services managed by this project.
# Expects each service to have a stop script at `scripts/stop`.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"

  services/ffc-demo-web/scripts/connected-stop
  services/ffc-demo-api-gateway/scripts/connected-stop
  services/ffc-demo-calculation-service/scripts/connected-stop
  services/ffc-demo-claim-service/scripts/connected-stop
  services/ffc-demo-payment-service/scripts/connected-stop
  services/ffc-demo-user-service/scripts/connected-stop
  scripts/stop-core
)
