#!/usr/bin/env sh

##
# Stop Core script
#
# Stop the supporting services this repository provides.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"

  docker-compose down -v
)

# Check whether ffc-demo network exists and is no longer in use
if [ ! -z "$(docker network ls --filter name=^ffc-demo$ --format={{.Name}})" ] \
  && [ "$(docker network inspect -f {{.Containers}} ffc-demo &>/dev/null)" = "map[]" ] \
; then
  echo "Removing ffc-demo network"
  docker network rm ffc-demo
fi
