#!/usr/bin/env sh

##
# Stop Core script
#
# Stop the supporting services this repository provides.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

# Check whether mine-support network needs creating
if [ -z "$(docker network ls --filter name=^mine-support$ --format={{.Name}})" ]; then
  echo "Creating mine-support Docker network"
  docker network create mine-support
fi

(
  cd "${projectRoot}"

  docker-compose down -v
)
