#!/usr/bin/env sh

##
# Update script
#
# Update the services managed by this project.
# Depends on git and scripts/build.
##

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"
  cd ..

  (cd "ffc-demo-web" && git pull)
  (cd "ffc-demo-claim-service" && git pull)
  (cd "ffc-demo-payment-service" && git pull)
  (cd "ffc-demo-payment-service-core" && git pull)
  (cd "ffc-demo-calculation-service" && git pull)
  (cd "ffc-demo-payment-web" && git pull)

  scripts/build
)
