#!/usr/bin/env sh

set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)

# Set Docker resource names managed by this script
jenkinsImage="ffc-demo-jenkins"

show_help() {
  echo "
Usage: scripts/jenkins/password [OPTION...]

Get the password for a Jenkins instance created by scripts/jenkins/start.

Options:
  -h, --help   display this help text
"
}

while :; do
  case $1 in
    -h|--help)   # Call "show_help" function to display a synopsis, then exit
      show_help
      exit
      ;;

    *)
      break
  esac

  shift
done

(
  cd "${projectRoot}"

  docker build \
    -t ${jenkinsImage} \
    ./jenkins
)
